print("Welcome to AI applications!")
print("What is your name?")
name = input()
print("Hello", name,"!" + "Nice to meet you!" + " What is your favorite programming language?")
language = input()
print(language + " is a great choice!")
